import fs from 'node:fs';
let source=fs.readFileSync('src/main.jsx','utf8');
source=source.slice(source.indexOf('function App(){'),source.indexOf("\ncreateRoot("));
source=source.replace('function App(){','export default function App(){');
source=source.replace('  const dialog=useRef(null);','');
const start=source.indexOf('  useEffect(()=>{\n    if(selected)');
const end=source.indexOf('  const copy=',start);
source=source.slice(0,start)+`  useEffect(()=>{
    const sync=()=>{const id=window.location.hash.match(/^#case\\/(.+)$/)?.[1];setSelected([...projects,experience].find(item=>item.id===id)||null);};
    sync();window.addEventListener('hashchange',sync);window.addEventListener('popstate',sync);
    return ()=>{window.removeEventListener('hashchange',sync);window.removeEventListener('popstate',sync);};
  },[]);
  useEffect(()=>{document.title=selected ? selected.name+' · 周天翊' : '周天翊 · 把洞察变成共鸣';},[selected]);
  const openProject=project=>{window.history.pushState({portfolioCase:true},'', '#case/'+project.id);setSelected(project);};
  const closeProject=()=>{setSelected(null);if(window.history.state?.portfolioCase)window.history.back();else window.history.replaceState(null,'', '#projects');};
`+source.slice(end);
source=source.replace("rotate(\u0024{(e.clientX-r.left-r.width/2)/65}deg)","rotate(\u0024{-7+(e.clientX-r.left-r.width/2)/65}deg)");
source=source.replace('一半数据思维，一半创意表达。','商业思维，创意表达，还有 AI 行动力。');
source=source.replace('在商业与人的连接处，寻找值得被讲述的故事。','在数据与故事之间，把想法变成真实的行动。');
source=source.replace('<div className="identity-card" ref={heroArt}>','<div className="hero-photo-slip"><img src="/media/personal-red-sm.webp" alt="周天翊的校园生活照" width="680" height="453"/><span>THINK / MAKE / FEEL</span></div><div className="identity-card" ref={heroArt}>');
source=source.replace('<span>01 / 27</span>','<span>EDITION 02</span>');
source=source.replace('PERSONAL PORTFOLIO — VOL.01','PERSONAL PORTFOLIO — VOL.02');
source=source.replace('<span>CONSUMER INSIGHT</span><Star/><span>BRAND STORYTELLING</span><Star/><span>MAKE IDEAS HAPPEN</span>','<span>DATA / STORY</span><Star/><span>THINK / MAKE</span><Star/><span>BUSINESS / CREATIVITY</span>');
source=source.replace('每一次实践，都是一次与真实需求的对话。','有原始作品，也有可追溯的项目记录。');
source=source.replace('点击卡片，展开项目','掀开封面，走进现场');
const gridStart=source.indexOf('<div className="project-grid">');
const gridEnd=source.indexOf('</section>',gridStart);
source=source.slice(0,gridStart)+`<div className="project-grid">{projects.filter(p=>filter==='全部'||p.type===filter).map(p=><ProjectCard key={p.id} project={p} onOpen={openProject}/>)}</div><p className="project-footnote">FIELD NOTES / 图形封面背后，是实际完成的研究、内容与活动。</p>`+source.slice(gridEnd);
const expStart=source.indexOf('      <section id="experience"');
const contactStart=source.indexOf('      <section id="contact"',expStart);
source=source.slice(0,expStart)+'      <Experience onOpen={openProject}/>\n      <About/>\n'+source.slice(contactStart);
const dialogStart=source.indexOf('    <dialog');
const dialogEnd=source.indexOf('</dialog>',dialogStart)+'</dialog>'.length;
source=source.slice(0,dialogStart)+'    <CaseStudy project={selected} onClose={closeProject}/>'+source.slice(dialogEnd);
const imports=`import React, { useEffect, useRef, useState } from 'react';
import { Arrow, Star } from './components/Icons';
import { projects, experience } from './data/projects';
import { ProjectCard } from './components/ProjectCard';
import { CaseStudy } from './components/CaseStudy';
import { Experience } from './components/Experience';
import { About } from './components/About';
`;
fs.writeFileSync('src/App.jsx',imports+source);
fs.writeFileSync('src/main.jsx',`import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './styles.css';
import './campaign.css';
createRoot(document.getElementById('root')).render(<App/>);
`);
